# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
#disqus: dbyll
#google_analytics: dbyll

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Julien Tap

description: explore --method=metagenomics gut::microbiota > data
author:
  name: Julien Tap
  email: julien.tap@free.fr
  github: tapj
  twitter: julientap
  #pinterest: asd123
  scholar: aYTQ-WkAAAAJ
  linkedin: julientap
  gplus: 116819383000559825436?rel=author
  bio: explore --method=metagenomics gut::microbiota > data
  #email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about_path: about.html
data_path: data.html
research_path: research_interest.html

BASE_PATH:
